version: "3"
services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/ssl/certs:ro

# Insert other containers you need
#
#  my-node-app:
#   [...]